### PR TITLE
fix: Gradle 7 builds for capacitor 3 as recommended

### PR DESCRIPTION
**Pull request by riderx**
As say here : https://capacitorjs.com/docs/updating/3-0#update-gradle-to-70
Gradle 7 is the minium version for android, in capacitor 3.
- [jcenter become deprecated](https://docs.gradle.org/current/userguide/upgrading_version_6.html)
- [`compile` have been removed](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal)

### CODE REVIEW

**Comment by pbowyer** [comment]
Thank you @riderx for this long-anticipated change! 

Could you please rebase your branch against `master` as Capacitor 3 support has been merged and is now the default.

**Comment by riderx** [comment]
@pbowyer done !

**Comment by riderx** [comment]
@pbowyer any news on that ?

**Comment by riderx** [comment]
@pbowyer hope for you too, it's never good when it last too much !

**Comment by pbowyer** [comment]
Thanks, tested and it works great 😀 

I think this is going to need the next release of camera preview to use a new major version number (`v2.0` to `v3.0`), as everyone must upgrade their Gradle project to use this change. I tested using your PR on a project using Gradle 4 and it broke, so I don't think it is possible to be backwards compatible?

**Comment by riderx** [comment]
@pbowyer yes it's not backwards compatible

**Pull request merged**
