### PR TITLE
Bugfix/93 preview not resized and displayed correctly when orientation changes

### PR DESCRIPTION
**Pull request by ryaa**

### CODE REVIEW

**Comment by riderx** [comment]
We have the same issue on ios i think @ryaa did you tried ?

**Comment by ryaa** [comment]
> We have the same issue on ios i think @ryaa did you tried ?

This should be fixed by this PR https://github.com/capacitor-community/camera-preview/pull/235. Please also see more details here https://github.com/capacitor-community/camera-preview/issues/232

**Comment by riderx** [comment]
@ryaa i did merge your both PR in this repo and published it :
https://github.com/Cap-go/camera-preview/tree/main
And this is still failing, when rotate the camera view take half the screen on ios

**Comment by ryaa** [comment]
> @ryaa i did merge your both PR in this repo and published it : https://github.com/Cap-go/camera-preview/tree/main And this is still failing, when rotate the camera view take half the screen on ios

@riderx, can you please try to install from my from _npm install ryaa/camera-preview#chore/my-latest-fixes-as-of-21-july-2022_
It includes fixes for iOS (https://github.com/capacitor-community/camera-preview/issues/232) and Android (https://github.com/capacitor-community/camera-preview/issues/93) and other people reported that everything seems to be working fine.

**Comment by riderx** [comment]
@ryaa after second round of testing i can see a improvement. but still not as expected.
The video don't rotate, then if i look down witht the phone and up again it rotate.

https://drive.google.com/file/d/1awylwmhwq5oDWvtA8LNpcXLInbjLMmLC/view?usp=sharing

**Comment by ryaa** [comment]
> https://drive.google.com/file/d/1awylwmhwq5oDWvtA8LNpcXLInbjLMmLC/view?usp=sharing

interesting. as I understand, the problem is on an Android device, right? I will try to double check to see if I can reproduce this problem. Right now, it seems to be working ok on my end.

**Comment by riderx** [comment]
@ryaa nope that on IOS

**Comment by ryaa** [comment]
> @ryaa nope that on IOS

This PR is for the fix for android and not iOS, so this is not relevant. Please note that the fix for iOS has already been merged to master and released - see https://github.com/capacitor-community/camera-preview/releases/tag/v3.1.1

**Comment by riderx** [comment]
@ryaa the title of the fix for iOS is "fixed the problem when photos taken in the landscape orientation are off" which is not my issue.
The issue I have is "preview not resized and displayed correctly when orientation changes" so that why I posted here.
I agree the original issue is connected to Android, but not the PR, which is the one i found.

**Comment by ryaa** [comment]
> @ryaa the title of the fix for iOS is "fixed the problem when photos taken in the landscape orientation are off" which is not my issue. The issue I have is "preview not resized and displayed correctly when orientation changes" so that why I posted here. I agree the original issue is connected to Android, but not the PR, which is the one i found. Sorry for the misunderstanding

ah.. got it... question - are you having the problem with the plugin installed from my branch (as I indicated above)? or is this the plugin installed from your branch?

**Comment by riderx** [comment]
@ryaa i tried with both and the behavior is the same, who seems normal since my branch is ISO as yours. ^^
While reading the code i don't see any change for the rotation issue in your commit for IOS, so that seems normal to me.

**Comment by ryaa** [comment]
> @ryaa i tried with both and the behavior is the same, who seems normal since my branch is ISO as yours. ^^ While reading the code i don't see any change for the rotation issue in your commit for IOS, so that seems normal to me.

Here is the change for iOS which fixes the rotation issue https://github.com/capacitor-community/camera-preview/pull/235/files
It should be there, in the plugin source code

**Comment by riderx** [comment]
@ryaa this is the fix for "fixed the problem when photos taken in the landscape orientation are off" , but you mean that also fix when you rotate the camera that rotate the preview?

**Comment by riderx** [comment]
@pbowyer when you have time to check that one, it seems important for android too :)

**Review by riderx — APPROVED** [review]

**Comment by pbowyer** [comment]
Thanks for checking these @riderx I will merge and make a new release 👍 

Re "@pbowyer when you have time to check that one, it seems important for android too :)" -- which one do you mean by "that one"?

**Comment by riderx** [comment]
thanks !

App MVP builder at Forgr <https://forgr.ee/>
Podcast host at INDIE MAKERS <https://indiemakers.fr>
Maker of Captime <https://captime.app> Crossfit timer app
 Creator of Capgo <https://capgo.app/> Capacitor OTA system

On August 29, 2022, Martin DONADIEU ***@***.***> wrote:
> Merged #238 <https://github.com/capacitor-community/camera-
> preview/pull/238> into master.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/capacitor-community/camera-preview/pull/238#event-
7278504235>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA7FGLZ3PIIHWFTLLHBOXZDV3SZHDANCNFSM54EL3XZQ>.
You are receiving this because you were mentioned.Message ID:
<capacitor-community/camera-
***@***.***>

**Pull request merged**
