### PR TITLE
Capacitor 3 upgrade

### PR DESCRIPTION
**Pull request by anth0**
The update for Capacitor 3 support.

I had to comment out some code related to video recording as it was just not compiling I don't know why.

### CODE REVIEW

**Comment by nick-krantz** [comment]
@anth0 I believe you'll have to update the iOS version in `CapacitorCommunityCameraPreview.podspec` as well

**Comment by anth0** [comment]
@nick-krantz good point. Looks like it's never been updated with the correct version. I'll do it.

**Comment by anth0** [comment]
No one to review and merge this? Is this plugin abandoned?

**Comment by nick-krantz** [comment]
@arielhernandezmusa Is there a plan to review and merge this PR?

**Comment by anth0** [comment]
@SalahAdDin I haven't checked the others. This version is the one I'm using on my app for now until this plugin is updated.

**Comment by nick-krantz** [comment]
@anth0 , @SalahAdDin I've tested this version with my app as well and it was behaving as it should. Though I'm not dependent on the recording video that is commented out.

**Comment by rymeier** [comment]
How can I go about helping to test and get this branch merged in. I am building a new platform on Capacitor. This plugin is pretty crucial to my go live and I've had to upgrade to Cap 3 for other plugins.

I am not entirely sure how to install this branch version into my local running project. If you can give me some tips I'm glad to contribute.

**Comment by pbowyer** [comment]
Thanks for your contribution, it was super helpful! We're at the point of publishing the Capacitor 3 integration so I'm closing this PR in favour of #183

**Pull request closed without merging**
