### PR TITLE
Add Opacity for web and Android, Support pinch/zoom for Android

### PR DESCRIPTION
**Pull request by johnbyrne7**
Added a method to manage opacity for the camera preview, for web and Android.  Useful for AR type applications.

Also added pinch/zoom support for Android.  

Works for both settings for CameraPreview.toBack (true and false)

### CODE REVIEW

**Comment by pbowyer** [comment]
Hi @johnbyrne7, thanks so much for this patch!

I'm working on getting Capacitor 3 support released first so there will be a little delay before this is merged in. In the meantime, could you rebase your pull request against the `capacitor-community:capacitor-3` branch please, which will become master once released?

**Comment by johnbyrne7** [comment]
Sure thing.  This week sometime I think.

A question though.  Out of habit, I formatted the Android java code in
Android Studio, so a few minor formatting changes are also included.  Do
you want those formatting changes also, or just the changes needed for the
patch?

thanks,
John Byrne

**Comment by pbowyer** [comment]
@johnbyrne7 I'd rather just the changes needed at this stage please. Once the Capacitor 3 version is released I'm going to get the code formatting standardised in the project. But waiting to do that until no PRs as it's makes so many changes!

**Comment by pbowyer** [comment]
Closing in favour of #178

**Pull request closed without merging**
